import { randomUUID } from "node:crypto";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, extname, isAbsolute } from "node:path";

import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import mammoth from "mammoth";

export type Phase4FilePilotWorkflowMode = "create" | "revise";

export type Phase4FilePilotWorkflowResult = {
  mode: Phase4FilePilotWorkflowMode;
  inputText: string;
  previousOutputText: string | null;
  outputText: string;
  warnings: string[];
};

export async function runPhase4FilePilotWorkflow(options: {
  mode: Phase4FilePilotWorkflowMode;
  inputPath: string;
  previousOutputPath?: string;
  outputPath: string;
}): Promise<Phase4FilePilotWorkflowResult> {
  assertDocxPath(options.inputPath, "inputPath");
  assertDocxPath(options.outputPath, "outputPath");
  if (options.mode === "revise") {
    if (!options.previousOutputPath) {
      throw new Error("previousOutputPath is required when revising a DOCX.");
    }
    assertDocxPath(options.previousOutputPath, "previousOutputPath");
  } else if (options.previousOutputPath !== undefined) {
    throw new Error("previousOutputPath is only valid when revising a DOCX.");
  }
  const input = await extractDocxText(options.inputPath);
  if (!input.text) throw new Error("Phase 4 Pilot input DOCX has no readable text.");
  const previous = options.mode === "revise"
    ? await extractDocxText(options.previousOutputPath!)
    : null;
  if (options.mode === "revise" && !previous?.text) {
    throw new Error("Phase 4 Pilot cannot revise an output without readable prior text.");
  }

  const document = new Document({
    creator: "ScopeGuard Phase 4 Pilot",
    title: options.mode === "create"
      ? "ScopeGuard Agent file workflow"
      : "ScopeGuard Agent file workflow revision",
    description: "Generated by an external test-only Agent toolchain; not a ScopeGuard document engine.",
    sections: [{
      children: [
        new Paragraph({
          heading: HeadingLevel.TITLE,
          children: [new TextRun("ScopeGuard Agent 文件工作流")],
        }),
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [new TextRun(options.mode === "create" ? "初稿" : "修订稿")],
        }),
        new Paragraph({
          children: [new TextRun({
            text: `已检查输入：${boundedText(input.text)}`,
          })],
        }),
        ...(previous ? [
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [new TextRun("上一版本摘要")],
          }),
          new Paragraph({
            children: [new TextRun(boundedText(previous.text))],
          }),
        ] : []),
        new Paragraph({
          children: [new TextRun({
            text: options.mode === "create"
              ? "版本 1：通过 Pi bash Tool 调用 docx 与 mammoth 创建并复查。"
              : "版本 2：读取上一版本与新输入后重新生成并复查。",
            bold: true,
          })],
        }),
      ],
    }],
  });
  const bytes = await Packer.toBuffer(document);
  await mkdir(dirname(options.outputPath), { recursive: true, mode: 0o700 });
  const temporaryPath = `${options.outputPath}.${randomUUID()}.tmp`;
  try {
    await writeFile(temporaryPath, bytes, { mode: 0o600 });
    await rm(options.outputPath, { force: true });
    await rename(temporaryPath, options.outputPath);
  } finally {
    await rm(temporaryPath, { force: true });
  }

  const output = await extractDocxText(options.outputPath);
  const expectedMarker = options.mode === "create" ? "版本 1" : "版本 2";
  if (!output.text.includes(expectedMarker) || !output.text.includes("已检查输入")) {
    throw new Error("Phase 4 Pilot output DOCX failed its post-write text validation.");
  }
  return {
    mode: options.mode,
    inputText: input.text,
    previousOutputText: previous?.text ?? null,
    outputText: output.text,
    warnings: [...input.warnings, ...(previous?.warnings ?? []), ...output.warnings],
  };
}

export async function readPhase4PilotDocxText(path: string): Promise<string> {
  assertDocxPath(path, "path");
  return (await extractDocxText(path)).text;
}

async function extractDocxText(path: string): Promise<{ text: string; warnings: string[] }> {
  const result = await mammoth.extractRawText({ buffer: await readFile(path) });
  const errors = result.messages.filter(({ type }) => type === "error");
  if (errors.length > 0) {
    throw new Error(`DOCX text extraction failed: ${errors.map(({ message }) => message).join("; ")}`);
  }
  return {
    text: normalizeText(result.value),
    warnings: result.messages.map(({ message }) => message),
  };
}

function assertDocxPath(path: string, field: string): void {
  if (!isAbsolute(path) || extname(path).toLowerCase() !== ".docx") {
    throw new Error(`${field} must be an absolute DOCX path.`);
  }
}

function normalizeText(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function boundedText(value: string): string {
  return value.length <= 4_000 ? value : `${value.slice(0, 3_997)}...`;
}
